// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXa41zNePQco8W4VEDRtEKeXgKd63xEw',
    appId: '1:391343557546:web:caac32a4694c8e8c38b9d3',
    messagingSenderId: '391343557546',
    projectId: 'signin-77324',
    authDomain: 'signin-77324.firebaseapp.com',
    storageBucket: 'signin-77324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjBJZR5qJ260Y0hGbX6C68wMunNvZconU',
    appId: '1:391343557546:android:a02a2971d3571ccb38b9d3',
    messagingSenderId: '391343557546',
    projectId: 'signin-77324',
    storageBucket: 'signin-77324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpjcs_TxV_ergqLayneCbNWjo8lAIPSCI',
    appId: '1:391343557546:ios:aaeb54fd8698786138b9d3',
    messagingSenderId: '391343557546',
    projectId: 'signin-77324',
    storageBucket: 'signin-77324.appspot.com',
    iosBundleId: 'com.example.googleSigninAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpjcs_TxV_ergqLayneCbNWjo8lAIPSCI',
    appId: '1:391343557546:ios:aaeb54fd8698786138b9d3',
    messagingSenderId: '391343557546',
    projectId: 'signin-77324',
    storageBucket: 'signin-77324.appspot.com',
    iosBundleId: 'com.example.googleSigninAuthFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVXa41zNePQco8W4VEDRtEKeXgKd63xEw',
    appId: '1:391343557546:web:db0c651bc509eed238b9d3',
    messagingSenderId: '391343557546',
    projectId: 'signin-77324',
    authDomain: 'signin-77324.firebaseapp.com',
    storageBucket: 'signin-77324.appspot.com',
  );
}
